# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Add tab completion for many Bash commands
if which brew > /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
	source "$(brew --prefix)/share/bash-completion/bash_completion";
elif [ -f /etc/bash_completion ]; then
	source /etc/bash_completion;
fi;

# Aliases
if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

# Custom prompt
if [ -f ~/.bash_prompt ]; then
  . ~/.bash_prompt
fi

# Local settings, not committed
if [ -f ~/.bash_local ]; then
  . ~/.bash_local
fi